// Mocks generated by Mockito 5.0.10 from annotations
// in flutter_movie_list/test/unit/movie_list_repository/movie_list_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:flutter_movie_list/modules/movie_list/models/movie_list_model.dart'
    as _i4;
import 'package:flutter_movie_list/modules/movie_list/repositories/movie_list_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [MovieListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieListRepository extends _i1.Mock
    implements _i2.MovieListRepository {
  MockMovieListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.MovieListModel>?> getMovie(int? page) =>
      (super.noSuchMethod(Invocation.method(#getMovie, [page]),
              returnValue: Future<List<_i4.MovieListModel>?>.value())
          as _i3.Future<List<_i4.MovieListModel>?>);
}
